### PR TITLE
Improvements for 1404

### PR DESCRIPTION
**Pull request by vskubriev**
This commit's reimplement service starting and restarting on ubuntu 14.04 and ubuntu 12.04 too.

I faced with problems:
1. of starting services on 14.04 because of renaming init scripts in 14.04
2. of service starting order (service must start after config created(changed) - we will want idempotency)

### CODE REVIEW

**Comment by vskubriev** [comment]
Hi Larry!

What about this pull request ?

**Comment by ceaser** [comment]
I'm wanted to test it first, but currently I'm out of town. I'll be able to try it out by next week.

**Comment by vskubriev** [comment]
Ok, I will wait for you tests. This is a true task before merge. I already use this improvements in production on 12.04 and 14.04 servers.

**Comment by tas50** [comment]
Any chance we can get a release with these changes?

**Comment by ceaser** [comment]
@tas50 just finished pushing a new update.

**Pull request merged**
